import Link from "next/link";
import { ArrowRight, Building2, Loader2, Search, Sparkles } from "lucide-react";
export function Header() { return <header className="border-b border-ink/10 bg-white/80 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><Link href="/" className="flex items-center gap-2 text-lg font-bold tracking-tight"><Building2 className="text-teal" /> Haven<span className="text-teal">Find</span></Link><nav className="hidden items-center gap-7 text-sm font-medium md:flex"><Link href="/properties" className="hover:text-teal">Explore homes</Link><Link href="/chat" className="hover:text-teal">Ask Haven AI</Link><Link href="/dashboard" className="rounded-full bg-ink px-5 py-2.5 text-white hover:bg-teal">Workspace</Link></nav></div></header>; }
export function Loading() { return <div className="flex min-h-40 items-center justify-center text-teal"><Loader2 className="animate-spin" /></div>; }
export function ErrorState({ message }: { message: string }) { return <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-800"><p className="font-semibold">We couldn’t load that</p><p className="mt-1 text-sm">{message}</p></div>; }
export function Empty({ message = "Nothing here yet." }) { return <div className="rounded-2xl border border-dashed border-ink/20 bg-white p-12 text-center text-sm text-ink/60"><Search className="mx-auto mb-3 text-teal" /><p>{message}</p></div>; }
export function PropertyCard({ property }: { property: import("../lib/types").Property }) { return <Link href={`/properties/${property.property_id}`} className="group overflow-hidden rounded-2xl bg-white shadow-soft transition hover:-translate-y-1"><div className="relative flex h-48 items-end bg-gradient-to-br from-teal/80 to-ink p-5 text-white">{property.image_url && <img src={property.image_url} alt="" className="absolute inset-0 h-full w-full object-cover opacity-75" />}<span className="relative rounded-full bg-white/20 px-3 py-1 text-xs backdrop-blur">{property.availability_status}</span></div><div className="p-5"><p className="text-xs font-semibold uppercase tracking-wider text-teal">{property.property_type} · {property.suburb}</p><h3 className="mt-2 text-lg font-semibold group-hover:text-teal">{property.title}</h3><p className="mt-2 line-clamp-2 text-sm text-ink/60">{property.description}</p><div className="mt-5 flex items-center justify-between text-sm"><span>{property.bedrooms} bd · {property.bathrooms} ba · {property.parking} car</span><strong>${property.price.toLocaleString()}</strong></div></div></Link>; }
export function ButtonLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="inline-flex items-center gap-2 rounded-full bg-teal px-5 py-3 text-sm font-semibold text-white hover:bg-ink">{children}<ArrowRight size={16} /></Link>; }
export function LogoMark() { return <div className="mb-6 flex items-center gap-2 text-sm font-semibold text-teal"><Sparkles size={16} /> Thoughtful property search</div>; }
